export const SEO = {
  siteName: "Flowdrop",
  siteUrl: "https://flowdrop.ai",
  title: "Flowdrop - Hire AI Agents | Build & Deploy AI Agents in Minutes",
  description: "Hire AI agents that work while you sleep. Flowdrop lets you build, deploy, and manage AI agents for any task — no code required.",
  image: "https://flowdrop.ai/website-preview.png",
  imageAlt: "Flowdrop - Hire AI Agents",
  locale: "en_US",
  twitterHandle: "@flowdrop",
  keywords: [
    "hire ai agents",
    "ai agents",
    "ai agent platform",
    "ai agent marketplace",
    "deploy ai agents",
    "agentic ai",
    "agentic tools",
    "build your own ai agent",
    "no-code automation",
    "workflow automation",
    "AI automation",
    "business automation",
    "automation platform",
  ],
  org: {
    name: "Flowdrop",
    description: "Flowdrop is the easiest way to hire AI agents. Build, deploy, and manage agents that automate any task — no code required.",
    foundingDate: "2024",
    logo: "https://flowdrop.ai/website-preview.png",
    sameAs: [
      "https://twitter.com/flowdrop",
      "https://linkedin.com/company/flowdrop",
    ],
  },
  schemas: {
    website: "Hire AI agents that work for you 24/7. Build and deploy AI agents in minutes with Flowdrop.",
    softwareApp: "AI agent platform that lets you hire, build, and deploy AI agents for any task in minutes.",
  },
} as const;
